version: '3.9'

services:

  frontend:
    build:
      context: ./
      dockerfile: ./docker/frontend/Dockerfile
    container_name: frontend
    volumes:
      - ./frontend:/app/frontend
    tty: true
    ports:
      - 8080:3000
    networks:
      - sample-app

  backend:
    build:
      context: ./
      dockerfile: ./docker/backend/Dockerfile
    container_name: backend
    volumes:
      - ./backend:/app/backend
    tty: true
    ports:
      - 8081:3000
    networks:
      - sample-app

networks:
  sample-app:
    external: true
